package spdvid.etvimageviewertest;

import spdvid.di03_tutoria01_componentesjavabeans.ETVImageViewerDI03;
import java.io.File;

/**
 *
 * @author Fer
 */
public class ETVImageViewerTest extends javax.swing.JFrame {
    private int fotoActiva;
    /**
     * Creates new form ETVImageViewerTest
     */
    public ETVImageViewerTest() {
        initComponents();
        setBounds(200, 0, 600, 600);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnPrev = new javax.swing.JButton();
        btnNext = new javax.swing.JButton();
        chkManual = new javax.swing.JCheckBox();
        lblInfoFoto = new javax.swing.JLabel();
        eTVImageViewerDI032 = new spdvid.di03_tutoria01_componentesjavabeans.ETVImageViewerDI03();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);

        btnPrev.setText("Anterior");
        btnPrev.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPrevActionPerformed(evt);
            }
        });
        getContentPane().add(btnPrev);
        btnPrev.setBounds(110, 240, 90, 23);

        btnNext.setText("Siguiente");
        btnNext.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNextActionPerformed(evt);
            }
        });
        getContentPane().add(btnNext);
        btnNext.setBounds(310, 240, 90, 23);

        chkManual.setText("Manual");
        chkManual.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                chkManualStateChanged(evt);
            }
        });
        getContentPane().add(chkManual);
        chkManual.setBounds(220, 240, 85, 20);

        lblInfoFoto.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        getContentPane().add(lblInfoFoto);
        lblInfoFoto.setBounds(140, 280, 220, 6);

        eTVImageViewerDI032.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        eTVImageViewerDI032.setSelectFotos(new spdvid.di03_tutoria01_componentesjavabeans.SelectFotos(new java.io.File[]{new File("C:/Users/Fer/Pictures/Saved Pictures/aad7d9fb-23de-44d5-b2a4-6248196f576f.jpg"),new File("C:/Users/Fer/Pictures/Saved Pictures/e22a8eaf-185d-4fe9-9952-f3c00c806adf.jpg"),new File("C:/Users/Fer/Pictures/Saved Pictures/eb27ba26-0e7b-4db1-abca-32625fbab781.jpg"),new File("C:/Users/Fer/Pictures/Saved Pictures/feea4926-2062-4cc4-a825-9859c1b5601e.jpg"),new File("C:/Users/Fer/Pictures/Saved Pictures/fit_FiestaPiraguas1.jpg")}));
        getContentPane().add(eTVImageViewerDI032);
        eTVImageViewerDI032.setBounds(40, 10, 460, 220);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnPrevActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPrevActionPerformed
        eTVImageViewerDI032.prevImage();
        eTVImageViewerDI032.repaint();        
    }//GEN-LAST:event_btnPrevActionPerformed

    private void btnNextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNextActionPerformed
        eTVImageViewerDI032.nextImage();
        eTVImageViewerDI032.repaint();        
    }//GEN-LAST:event_btnNextActionPerformed

    private void chkManualStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_chkManualStateChanged
        if (chkManual.isSelected()==true){
            btnPrev.setEnabled(true);
            btnNext.setEnabled(true);
        }else{
            btnPrev.setEnabled(false);
            btnNext.setEnabled(false);
            eTVImageViewerDI032
                    .timerFoto();
        }
    }//GEN-LAST:event_chkManualStateChanged

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ETVImageViewerTest.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ETVImageViewerTest.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ETVImageViewerTest.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ETVImageViewerTest.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ETVImageViewerTest().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnNext;
    private javax.swing.JButton btnPrev;
    private javax.swing.JCheckBox chkManual;
    private spdvid.di03_tutoria01_componentesjavabeans.ETVImageViewerDI03 eTVImageViewerDI032;
    private javax.swing.JLabel lblInfoFoto;
    // End of variables declaration//GEN-END:variables
}
